#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Oct 19 23:26:43 2018

@author: eejups
"""

import sys
import pandas as pd
import numpy as np
from datetime import datetime
import time
import multiprocessing
import webbrowser
import MySQLdb

db = MySQLdv.connect(host="10.90.1/77", user ="ghtsql", passwd ="cct1ng", db = "GHT_GG")
cursor = db.cursor()

def Download(Name):
    csv_url = 'http://quer1a' + Name + ''
    chrome_path = 'C://Program Files (x86)/Google/Chrome/Applicaiton/chrome.exe %s'
    webbrowser.get(chrome_path).open_new_tab(csv_url)
    
def FindDivNames(currentname):
    IsWrong = 1
    try:
        OldPath = "select SecurityID, Price from All_Vols_copy where SecurityID = " + str(currentname['SecurityID]) + " and Date = 20180727"
        OldPrice = pd.read_sql_query(OldPath, db)
        OldPrice = round(float(OOldPrice.loc[0,'Price']),2)
        newPath = 'C:\\Users\\eejup\\' + str(currentname['Name']) + ".csv"
        Newfile = pd.ead_csv(newPath)
        
